version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building java
      - cd pension-disbursement-service
      - mvn clean package
      - echo Building the docker image
      - docker build -t pension-disbursement-service .
      - docker tag pension-disbursement-service 156962844638.dkr.ecr.us-east-1.amazonaws.com/pension-management-portal-877629:pension-disbursement-service
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 156962844638.dkr.ecr.us-east-1.amazonaws.com/pension-management-portal-877629:pension-disbursement-service
      - echo Writing definition files
      - printf '[{"name":"pension-disbursement-service-container","imageUri":"%s"}]' 156962844638.dkr.ecr.us-east-1.amazonaws.com/pension-management-portal-877629:pension-disbursement-service > taskdefinition.json

artifacts:
  files: pension-disbursement-service/taskdefinition.json